name: Bump homebrew-cask 

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag name to bump the formula to'
        required: true

jobs:
  manual-cask-bump:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Bump cf-terraforming cask in cloudflare/homebrew-cloudflare
        uses: macauley/action-homebrew-bump-cask@v1
        with:
          token: ${{ secrets.BUMP_CASK_TOKEN }}
          tap: cloudflare/homebrew-cloudflare
          cask: cf-terraforming
          livecheck: true
          dryrun: false
